// Generated by scripts/sql-type.mjs
// Rerun `pnpm field-type` to regenerate this file.
export type AnnotationItem<Base> = Base & Record<"itemType", "annotation">;
export type AttachmentItem<Base> = Base &
  Record<"itemType", "attachment"> &
  Partial<Record<"title" | "url", string> & Record<"accessDate", Date>>;
export type NoteItem<Base> = Base & Record<"itemType", "note">;
export const nonRegularItemTypes = [
  "attachment",
  "note",
  "annotation",
] as const;
