// Generated by scripts/sql-type.mjs
// Rerun `pnpm field-type` to regenerate this file.
import type { GeneralItem } from "./item";
export type AttachmentItem = GeneralItem &
  Record<"itemType", "attachment"> &
  Partial<Record<"title" | "url", string> & Record<"accessDate", Date>>;
export type NoteItem = GeneralItem & Record<"itemType", "note">;
export type AnnotationItem = GeneralItem & Record<"itemType", "annotation">;
