// Generated by scripts/sql-type.mjs
// Rerun `pnpm field-type` to regenerate this file.
import type { Item } from "./item.js";
export type AttachmentItem = Item &
  Record<"itemType", "attachment"> &
  Partial<Record<"title" | "url", string> & Record<"accessDate", Date>>;
export type NoteItem = Item & Record<"itemType", "note">;
export type AnnotationItem = Item & Record<"itemType", "annotation">;
