import obPlugin from "@aidenlx/esbuild-plugin-obsidian";
import builtins from "builtin-modules";
import { build } from "esbuild";
import { lessLoader } from "esbuild-plugin-less";
import escape from "escape-string-regexp";
import { promises } from "fs";

import inlineWorker from "./scripts/inline-worker.mjs";
import { getConfigDirExec, libName } from "./src/const.js";
const { readFile } = promises;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/
`;
const pathToInstallGuide = `${process.cwd()}/src/install-guide`;

const getPatchedBindingCode = (showGuide) => `
try {
  var path = require("path").join(${getConfigDirExec},"${libName}"),
    binding = require(path);
  binding.path = path;
  return binding;
} catch (err) {
  ${
    showGuide
      ? `err.code === "MODULE_NOT_FOUND" && require("${pathToInstallGuide}")();`
      : ""
  }
  throw err;
}
`;

/**
 * Patch the binding code to point module to the correct path
 * @param {boolean} worker in worker mode, skip the install guide
 * @returns {import("esbuild").Plugin}
 */
const patchBindings = (worker = false) => ({
  name: "patch-bindings",
  setup: (build) =>
    build.onLoad(
      { filter: /node_modules\/bindings\/bindings\.js$/ },
      async (args) => ({
        contents: (await readFile(args.path, "utf8")).replace(
          `// Get the module root`,
          getPatchedBindingCode(!worker),
        ),
      }),
    ),
});

const isProd = process.env.BUILD === "production";

/** @type import("esbuild").BuildOptions */
const opts = {
  bundle: true,
  watch: !isProd,
  platform: "browser",
  external: ["obsidian", "electron", ...builtins],
  format: "cjs",
  mainFields: ["browser", "module", "main"],
  sourcemap: isProd ? false : "inline",
  minify: isProd,
  define: {
    "process.env.NODE_ENV": JSON.stringify(process.env.BUILD),
  },
  loader: {
    ".sql": "text",
  },
};
try {
  await build({
    ...opts,
    entryPoints: ["src/zt-main.ts"],
    banner: { js: banner },
    outfile: "build/main.js",
    plugins: [
      lessLoader(),
      inlineWorker(
        {
          ...opts,
          external: [...builtins],
          plugins: [patchBindings(true)],
          format: "cjs",
        },
        [[new RegExp(escape(getConfigDirExec), "g"), 0]],
      ),
      obPlugin(),
      patchBindings(),
    ],
  });
} catch (err) {
  console.error(err);
  process.exit(1);
}
