// Generated by scripts/sql-type.mjs
// Rerun `pnpm db-type` to regenerate this file.
import type * as DB from "./db-types.js";
declare module "@aidenlx/knex/types/tables" {
  interface Tables {
    baseFieldMappings: Required<DB.BaseFieldMappings>;
    baseFieldMappingsCombined: Required<DB.BaseFieldMappingsCombined>;
    charsets: Required<DB.Charsets>;
    collectionItems: Required<DB.CollectionItems>;
    collectionRelations: Required<DB.CollectionRelations>;
    collections: Required<DB.Collections>;
    creators: Required<DB.Creators>;
    creatorTypes: Required<DB.CreatorTypes>;
    customBaseFieldMappings: Required<DB.CustomBaseFieldMappings>;
    customFields: Required<DB.CustomFields>;
    customItemTypeFields: Required<DB.CustomItemTypeFields>;
    customItemTypes: Required<DB.CustomItemTypes>;
    deletedCollections: Required<DB.DeletedCollections>;
    deletedItems: Required<DB.DeletedItems>;
    deletedSearches: Required<DB.DeletedSearches>;
    feedItems: Required<DB.FeedItems>;
    feeds: Required<DB.Feeds>;
    fieldFormats: Required<DB.FieldFormats>;
    fields: Required<DB.Fields>;
    fieldsCombined: Required<DB.FieldsCombined>;
    fileTypeMimeTypes: Required<DB.FileTypeMimeTypes>;
    fileTypes: Required<DB.FileTypes>;
    fulltextItems: Required<DB.FulltextItems>;
    fulltextItemWords: Required<DB.FulltextItemWords>;
    fulltextWords: Required<DB.FulltextWords>;
    groupItems: Required<DB.GroupItems>;
    groups: Required<DB.Groups>;
    itemAnnotations: Required<DB.ItemAnnotations>;
    itemAttachments: Required<DB.ItemAttachments>;
    itemCreators: Required<DB.ItemCreators>;
    itemData: Required<DB.ItemData>;
    itemDataValues: Required<DB.ItemDataValues>;
    itemNotes: Required<DB.ItemNotes>;
    itemRelations: Required<DB.ItemRelations>;
    items: Required<DB.Items>;
    itemTags: Required<DB.ItemTags>;
    itemTypeCreatorTypes: Required<DB.ItemTypeCreatorTypes>;
    itemTypeFields: Required<DB.ItemTypeFields>;
    itemTypeFieldsCombined: Required<DB.ItemTypeFieldsCombined>;
    itemTypes: Required<DB.ItemTypes>;
    itemTypesCombined: Required<DB.ItemTypesCombined>;
    libraries: Required<DB.Libraries>;
    noteBackups: Required<DB.NoteBackups>;
    proxies: Required<DB.Proxies>;
    proxyHosts: Required<DB.ProxyHosts>;
    publicationsItems: Required<DB.PublicationsItems>;
    relationPredicates: Required<DB.RelationPredicates>;
    retractedItems: Required<DB.RetractedItems>;
    savedSearchConditions: Required<DB.SavedSearchConditions>;
    savedSearches: Required<DB.SavedSearches>;
    settings: Required<DB.Settings>;
    storageDeleteLog: Required<DB.StorageDeleteLog>;
    syncCache: Required<DB.SyncCache>;
    syncDeleteLog: Required<DB.SyncDeleteLog>;
    syncedSettings: Required<DB.SyncedSettings>;
    syncObjectTypes: Required<DB.SyncObjectTypes>;
    syncQueue: Required<DB.SyncQueue>;
    tags: Required<DB.Tags>;
    translatorCache: Required<DB.TranslatorCache>;
    users: Required<DB.Users>;
    version: Required<DB.Version>;
  }
}
